### ISSUE TITLE
rename support for sub-directories

### ISSUE THREAD

**Issue by gilv** [CODAIT/stocator#111]
Current rename implementation works on the objects only.
We should extend it and support rename on the sub-directories, for example

container/a/b/c/data_1.txt
container/a/b/c/data_2.txt
container/a/b/c/data_3.txt
container/a/b/c/data_4.txt

And now we want to rename container/a/b/c to container/a/b/d. The implementation will need to handle

rename container/a/b/c/data_1.txt to container/a/b/d/data_1.txt
rename container/a/b/c/data_2.txt to container/a/b/d/data_2.txt
rename container/a/b/c/data_3.txt to container/a/b/d/data_3.txt
rename container/a/b/c/data_4.txt to container/a/b/d/data_4.txt

**Comment by gilv** [comment]
@djalova can you please check it? thanks

**Comment by djalova** [comment]
@gilv Do we want this to be the default behavior?

**Comment by gilv** [comment]
@djalova Yes, for rename. It suppose to check first if the src is a sub-directory and then copy all what is listed under this sub-directory

**Comment by djalova** [comment]
@gilv Should we enforce that object to rename ends with a "/" if the user wants to rename a directory?
