### ISSUE TITLE
FileSystem.getChecksum should return the checksum and not null

### ISSUE THREAD

**Issue by gilv** [CODAIT/stocator#116]
The issues comes when using Stocator via FileSystem API directly.
For example, the following Java code upload an object

`FileSystem fs = null;
       String p = "swift2d://container.bmtest1/some.data";
       try {
        fs = FileSystem.get(URI.create(p), mConf);
       } catch ( IOException e) {
        e.printStackTrace();
       }
       try {
        FSDataOutputStream out =  fs.create(new Path(p));
        out.write("abcdefgh".getBytes());
        out.close();
       } catch (Exception e) {
e.printStackTrace();
} `

User might want to verify that object created successfully and call FileSystem.getChecksum.
However current code will return null, which seems like a bug. 
We need to return the checksum.

**Comment by gilv** [comment]
@djalova Can you see it please? I guess the checksum is the hash returned by the object store, after the object was created with 201 status.

**Comment by djalova** [comment]
@gilv Can I get a stack trace of this? I don't see an exception when I try to run the code above as a test.

**Comment by gilv** [comment]
@djalova The code above doesn't produce any exception. But if you will run that code and then call fs.getChecksum() it will return null and not the real check sum of the object

**Comment by djalova** [comment]
@gilv I'm not sure if this method is meant to be used that way. Calling fs.getChecksum() returns a ChecksumFile object. If we just want to retrieve the etag for a an object there might be a better way.
