### ISSUE TITLE
Issue with SwiftOutputStream exhaust http pool

### ISSUE THREAD

**Issue by airbots** [CODAIT/stocator#123]
Current stocator code may cause http client exhaust http pool corresponding job hanging if there are highly concurrent small writes. We need to close each response after it is not used. We know that JVM GC will do it for users, however, if the requests is coming much faster than GC recycle period, job hanging happens.

**Comment by gilv** [comment]
@airbots thanks. interesting observation. do you have suggestion how to fix this in Stocator?

**Comment by airbots** [comment]
Sure, I can submit a path this week. Thanks.

**Comment by airbots** [comment]
Sorry about the late update, pull request is here: https://github.com/SparkTC/stocator/pull/138

**Comment by gilv** [comment]
@Fokko is this relevant to what you observed?

**Comment by Fokko** [comment]
Hi @gilv This looks different. We don't see any signs of exhaustion. We're not super sure if it Stocator or Spark itself, this is what we're figuring out now.

**Comment by Fokko** [comment]
I'm sorry for not getting back @gilv. I don't think this is relevant to what we've seen. Right now, we decided to leave it for now. Will open a new issue when we have new insights.
