### ISSUE TITLE
rename with COS

### ISSUE THREAD

**Issue by cjolif** [CODAIT/stocator#182]
We are using IBM Cloud Object Storage. We were using it with S3 compatibility layer and we switched to using Stocator with COS as it sounded a good idea to be as close as possible to the underlying Object Storage. Things were "ok" until we realized we were facing issues in some cases and we discovered this was because COS client is not implementing rename (always return false).

Is there a short term plan to add it or should we look into switching back to S3 compatible APIs?

**Comment by cjolif** [comment]
Ok thanks for the feedback. 

I guess as it was provided in the Swift client it could have made sense to get parity with the COS one but if you are not going to provide it we will look into alternate path.

**Comment by gilv** [comment]
@cjolif there was no rename in Stocator for Swift.. why you need rename, by the way?

**Comment by cjolif** [comment]
@gilv I never used Swift version but I saw: https://github.com/CODAIT/stocator/blob/master/src/main/java/com/ibm/stocator/fs/swift/SwiftAPIClient.java#L873. That's why I thought it was supported.

I'm not using rename directly but through a library that is using it.

**Comment by gilv** [comment]
@cjolif it was very limited supported rename, that was not used as far as i know. I also think it only made possible to rename single object. The whole point of Stocator is to avoid rename flows for analytic originated scenarios. It would be good to understand what kind of rename you expect? Rename of objects? Rename of directories? Does your client need rename of temporary written objects?
