### ISSUE TITLE
Spark append-mode throws FileAlreadyExistsException

### ISSUE THREAD

**Issue by RoeeShlomo** [CODAIT/stocator#190]
https://github.com/CODAIT/stocator/commit/35d7818c5dd0e3f2ea13d4bc3338aaa14c3bff31 introduced a bug in append mode. When writing in append mode the operation always fails with FileAlreadyExistsException:
```
Name: org.apache.hadoop.fs.FileAlreadyExistsException
Message: mkdir on existing directory cos://...
```

Steps to reproduce:
```
spark.range(10).write.mode("append").parquet("cos://yourbucket/yourobject")
spark.range(10).write.mode("append").parquet("cos://yourbucket/yourobject")
```

**Comment by gilv** [comment]
This is already resolved in the master branch. Fix will be released with 1.0.20
