### ISSUE TITLE
Throughput issues

### ISSUE THREAD

**Issue by martijnnanne** [CODAIT/stocator#202]
Hortonworks, stocator, swift and throughput issues

We are facing an issue in the combination of stocator, spark, hortonworks and the swift object store. We are not able to get the maximum throughput on all our machines when loading a large file from the swift object store into hdfs in a spark session.

**Some context:**

Hortonworks data platform version: 2.6
Spark version: 2.2
Stocator version: tried with multiple stocator versions (1.0.16, 1.0.23, 1.0.25)

Our cloud provider provides us with a 1gbit bandwidth.

**Reproducible issue**

The goal we want to accomplish is that we can have maximum throughput on all our hadoop machines where containers are deployed when we load a file from swift in a spark session. 

When we use the swift CLI to download a file on one of our hadoop machines (a datanode) the network graph will look like this:

The exact command: swift download testswift --prefix test --output-dir /tmp/

The throughput pattern on this machine now looks like this:

<img width="1411" alt="cli" src="https://user-images.githubusercontent.com/41899559/45810783-c12af100-bccb-11e8-9def-062d69f97aef.png">

The peak in the beginning is our 2gbit “burst” throughput.

We can see this behavior on all our hadoop machines, and it is also stable when we download a file from swift through the swift CLI on multiple machines at the same time. This means that on **all machines** that are performing the CLI download command we see a **120mb/s throughput**. 

Now we turn to our hadoop setup. 

The scala script we are using is the following:

```
from pyspark import SparkConf
from pyspark.sql import SparkSession

spark = SparkSession.builder.config("spark.hadoop.fs.swift2d.service.test.public", "false").appName("test").getOrCreate()

spark.read.format("text").load("swift2d://testswift.test/test").count()
// Count to trigger the load from swift
```

We run this script on the same hadoop machine (a datanode) as we just ran our CLI swift download command. We submit this job throught the following command:

spark-submit --num-executors 10 --executor-memory --jars stocator-1.0.16-SNAPSHOT-jar-with-dependencies.jar --name fokko --conf spark.dynamicAllocation.enabled=false --master local[*] run.py 

The throughput pattern now looks like this:

<img width="1420" alt="datanode_single_session" src="https://user-images.githubusercontent.com/41899559/45810793-cbe58600-bccb-11e8-97b2-c050217c0492.png">

As you can see, we have less throughput then 120mb/s (on avg it’s about 75 mb/s).

We are now going to execute the same script on the namenode of our hadoop cluster.

<img width="1408" alt="namenode_single_session" src="https://user-images.githubusercontent.com/41899559/45810823-de5fbf80-bccb-11e8-9b32-709954d37c73.png">

We now do get our expected throughput. 

**Issue / Question 1: when trying to load data from swift, through stocator and a spark session, why do we get our maximum throughput on the namenode but not on our datanode?**

Next we perform an experiment where we start the script both on the namenode and one one of our datanodes. Remember, these are two different spark sessions on two different machines.

We now see the following network behavior:

Namenode:

<img width="1419" alt="namenode_multiple_sessions" src="https://user-images.githubusercontent.com/41899559/45810845-ee779f00-bccb-11e8-99d0-b60078860ef9.png">

Datanode:

<img width="1404" alt="datanode_multiple_sessions" src="https://user-images.githubusercontent.com/41899559/45810853-f33c5300-bccb-11e8-986e-2d8040999c59.png">

We clearly see that the session on the datanode is affecting the session on the namenode and vice versa. Another interesting observation is that when the session on the namenode ends, the throughput on the datanode clearly rises. 

When we add more sessions, or distribute a session over multiple machines through yarn, we can see the same behavior: containers loading data over multiple machines affect the throughput on other machines. Resulting in the fact that we eventually only have 8 mb/s on each machine if we start a session with 100 containers on our cluster of 12 machines.

**Issue / Question 2: why do sessions loading data from swift, through spark/stocator negatively affect the throughput on other nodes when “downloading containers” are deployed over multiple nodes.**

I hope the situation is clear, I am happy to provide any information needed to solve this issue.

**Comment by martijnmobpro** [comment]
We finally found a solution to this problem. It turned out that hdp (installed with Ambari) used jdk1.8.0_112 and caused these issues. After (manually) setting JAVA_HOME in ambari to version 1.8.0_181 the issues were resolved.

I am not sure if Stocator has an issue with this version of java, might be interesting to look in to.

However, this issue can be closed.

**Comment by gilv** [comment]
@martijnmobpro thanks... i suspected this doesn't related Stocator, but still was checking. I am glad it's resolved now. Stocator depends on all kind of libraries, like HTTPClient, perhaps the issues comes from there with this particular Java version. 
Thanks for the information
