### ISSUE TITLE
Incorrect encoding specified for listing objects in ibm-sdk-1-34

### ISSUE THREAD

**Issue by dpittner** [CODAIT/stocator#215]
request.withEncodingType("UTF-8"); is incorrect

**Comment by gilv** [comment]
@dpittner @cmuchinsky we had this utf-8 because of this https://github.com/CODAIT/stocator/issues/171
So I assume its not needed anymore?

**Comment by cmuchinsky** [comment]
@gilv setting the encoding type is still needed to fix the `+` in key issue, however the value `UTF-8` is no longer valid, the server now requires it to be set to `url`, whereas in the past setting it to anything was valid.
