### ISSUE TITLE
Slowness when querying data(parquet) from COS

### ISSUE THREAD

**Issue by bharath0208** [CODAIT/stocator#221]
We have a SQL Engine tool similar to spark SQL which queries data from COS. We have CSV data close to 1 TB in size which we have compressed to parquet format(250GB). We are running this SQL engine tool on k8's distributed in multiple locations of Dallas. At first, we had a very small cluster with just 15 worker nodes at which we were seeing a response time of less than 1 min when running queries. We then scaled our cluster from 15 to 50 k8 nodes and now the response time for queries instead of going down has increased furthermore. We have checked from the k8, network, and COS side. They seem to suggest that this might be a problem at the client-side. But we are using stocator lib and hive(metastore) to read data in COS and then perform the logic in the query. 

Is there any default parameter in stocator that has to be tweaked when working with large sets of parquet files for getting a better response time.  What API implementation is being used at the back end to read the data from COS.  Is there any chance that this might be causing a problem when reading parquet data from COS.

**Comment by bharath0208** [comment]
This is what the IBM COS team has to say 
```
There appear to be two separate problems: one is high client wait times which may be a combination of client side and/or network induced delays. Secondly there is a workflow issue that they are making many simultaneous read requests for data from the same object which is stored in the same are of disk and this is causing a contention issue which is resulting in high storage wait times. The second issue in particular may be related to the client that they are using. I don;t know if it is feasible for them to read these large objects using fewer larger read requests which may result in longer latencies per request but less contention due to fewer overlapping requests for the same area of storage.```

**Comment by gilv** [comment]
@bharath0208 How many partitions do you have for the Parquet file and how the work is being divided between the workers as there shouldn't be contention on the same object?  The high client wait times are possibly related to the network config of the k8s cluster

**Comment by bharath0208** [comment]
@gilv  We are having different folders inside our bucket each with 7-10 files inside them. These files vary in size. Few folders are having files in KB, few in MB and few files are in GB's). The work is divided equally on all the k8 nodes as our SQL engine splits the stage onto all the nodes in which they are deployed. This means that each subset of a stage running on a node would fetch the data from COS using stocator lib.

**Comment by michaelfactor** [comment]
@bharath0208 so on a given stage could multiple workers be processing the same multi GB object?  If so, partitioning your Parquet file into ~64MB objects might address the contention.
