### ISSUE TITLE
Using Stocator for Amazon S3  writing

### ISSUE THREAD

**Issue by mfeiman** [CODAIT/stocator#222]
We'd like to try Stocator on Amazon S3 to write large parquet file - currently running in performance issues most likely related to well-known output commiter performance issue
(and EMR optimized commiter is not available option in our case). 
So can the stocator connector be used in Spark application to read/write parquet files to Amazon S3 ? Will it helps with performance in such case? Then how access credentials should be configured for Amazon S3?  Would be great if somebody could point me to example of such configuration for Stocator.

**Comment by gilv** [comment]
@mfeiman Stocator officially supported for IBM Cloud Object Storage. You can try Stocator with Amazon S3, just configure access key, secret key, configure endpoint to the Amazon S3 endpoint, but this is not something we tested or work with.

**Comment by gilv** [comment]
we can reopen it again if needed
