### ISSUE TITLE
How do you use stocator on an IBM Watson Studio Jupyter notebook?

### ISSUE THREAD

**Issue by sgop001** [CODAIT/stocator#226]
I understand that stocator is pre-installed on the Jupyter notebooks present on IBM cloud.

Say I have a bucket 'bucket-name-vers1' and a set of credentials, how do I go about writing a file to the same? Do I need to set up the credentials on the notebook for connecting the bucket to stocator? If so, please tell me how.

For eg.. I want to write a file to the bucket then what would it's path look like?

Thanks,
sp

**Comment by gilv** [comment]
@sgop001 you should address those questions to IBM Watson Studio support, etc. Here we maintain Stocator project itself and the issues around it. Thanks

**Comment by sgop001** [comment]
Can you please give me some example usage anyways? Maybe a small snippet on the IBM cloud on your side and if it is able to work for you then please share it here?

The reason I'm asking is because there is obviously some kind of setup (credentials for cloud storage access if the cloud storage you're using is not directly related to your project, I might be wrong on the second part though) required to use stocator (even on IBM Watson Studio) but none of the tutorials online seem to work for the same.

There's nothing specifically in the docs either. It would be very helpful if you could try this out and share the results here.

**Comment by sgop001** [comment]
Everything I try seems to throw some sort of error.. either the cos filesystem is not found or something else. I've tried everything..

I've settings within SparkContext object, tried using the 'filesystem.service-name' schema etc. nothing works
