### ISSUE TITLE
need help:how to list directories/folders in a vault using stocator

### ISSUE THREAD

**Issue by nkurn** [CODAIT/stocator#237]
I need to do this using spark/scala. I am able to access files but I need to list files using wildcards
eg.  /*/*/*.gz in a vault.

**Comment by nkurn** [comment]
I need to list directories and access files using wildcards for directories like /*/*/*.gz

**Comment by gilv** [comment]
@nkurn you can use * already. What is the issue?

**Comment by nkurn** [comment]
sorry, my mistake it is working, I will close this.

thanks for the quick response!

**Comment by nkurn** [comment]
Hi my mkdir is failing I opened bug # 272
Can someone please look
