### ISSUE TITLE
No AbstractFileSystem configured for scheme: cos

### ISSUE THREAD

**Issue by theathibm** [CODAIT/stocator#241]
I'm successfully using COS storage for saving parquet files via Spark Dataframes similar to the following:

- **newWeatherDF.write.format("csv").parquet("cos://..../ingested//data.parquet")**

However, now I'm trying to use DeltaLake from DataBricks and when running the following line in pyspark I get an error:

- Failing Line :       **newDF.write.format("delta").save("cos://.../ingested/delta/data.delta")**

- Error:       **org.apache.hadoop.fs.UnsupportedFileSystemException: fs.AbstractFileSystem.cos.impl=null: No AbstractFileSystem configured for scheme: cos**

Any ideas on how to config HDFS to use COS,

Thank,
Terry

**Comment by gilv** [comment]
@guykhazma can you please comment here? thanks

**Comment by guykhazma** [comment]
Hi @theathibm,

Seems like you didn't configure COS in the Hadoop Configuration.
You can use this for example:
```python
# setup the environment
hconf = spark.sparkContext._jsc.hadoopConfiguration()
# configure Stocator
hconf.set("fs.stocator.scheme.list", "cos")
hconf.set("fs.cos.impl", "com.ibm.stocator.fs.ObjectStoreFileSystem")
hconf.set("fs.stocator.cos.impl", "com.ibm.stocator.fs.cos.COSAPIClient")
hconf.set("fs.stocator.cos.scheme", "cos")

# for more info on how to config credentials see https://github.com/CODAIT/stocator
# see https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-endpoints for the list of endpoints
hconf.set("fs.cos.service.endpoint" ,"http://s3.us-south.objectstorage.softlayer.net")
hconf.set("fs.cos.service.access.key", "<accessKey>")
hconf.set("fs.cos.service.secret.key","<secretKey>")
```
For more authentication options (IAM) please refer to the [README](https://github.com/CODAIT/stocator/blob/master/README.md).

To use DeltaLake with COS you can use the `COSLogStore` implementation as explained in this [PR](https://github.com/delta-io/delta/pull/302).
