### ISSUE TITLE
Did not notice an improve of performance when upload a CSV to COS with scala & spark

### ISSUE THREAD

**Issue by ImErick** [CODAIT/stocator#249]
Hi guys,
Do you know if I miss something in the hadoop configuration? I also add the last 4 code lines and still have the same perfomance

    sparkContext.hadoopConfiguration.set("fs.stocator.scheme.list", COS_SCHEME)
    sparkContext.hadoopConfiguration.set("fs.cos.impl", STOCATOR_FS)
    sparkContext.hadoopConfiguration.set("fs.stocator.cos.impl", STOCATOR_COS_API)
    sparkContext.hadoopConfiguration.set("fs.stocator.cos.scheme", COS_SCHEME)
    sparkContext.hadoopConfiguration.set("fs.cos." + SERVICE + ".iam.api.key", COS_API_KEY_ID)
    sparkContext.hadoopConfiguration.set("fs.cos." + SERVICE + ".iam.service.id", COS_RESOURCE_CRN)
    sparkContext.hadoopConfiguration.set("fs.cos." + SERVICE + ".endpoint", COS_ENDPOINT)
    sparkContext.hadoopConfiguration.set("fs.cos." + SERVICE + ".iam.api.token", COS_AUTH_ENDPOINT)
    sparkContext.hadoopConfiguration.set("fs.cos." + SERVICE + ".access.key", ACCESS_KEY)
    sparkContext.hadoopConfiguration.set("fs.cos." + SERVICE + ".secret.key", SECRET_KEY)

    sparkContext.hadoopConfiguration.set("fs.cos.fast.upload", "true")
    sparkContext.hadoopConfiguration.set("fs.cos.atomic.write", "true")
    sparkContext.hadoopConfiguration.set("fs.cos.multipart.size", SIZE_VALUE)
    sparkContext.hadoopConfiguration.set("fs.cos.multipart.threshold", THRESHOLD_VALUE)
  

Where stocator values in the SIZE_VALUE and THRESHOLD_VALUE are "5242880"
And the write operation is:

```
finalDataFrame
        .coalesce(1)
        .write.mode(SaveMode.Overwrite)
        .format(outputFileFormat) // csv
        .option("timestampFormat", "yyyy-MM-dd HH:mm:ss")
        .option("quoteAll", "true")
        .save(fullPathInCOS)
```

So, did I miss somenting else?
Thanks in advance for your help

**Comment by gilv** [comment]
@ImErick coalesce(1) means you are taking ALL the data from ALL the partitions and move it into single partition. In this case you have a single file that you persist in object storage. So if you use Stocator or another connector you will not notice much difference. However .coalesce(1) is not how Big Data engines suppose to work. The whole idea is to have parallel datasets and not entire dataset into single machine memory. This is wrong usage.

**Comment by ImErick** [comment]
Yeah, but what can be the best approach in order to process all my data (in partitions of course) and after that have a single CSV file that will send to COS using Stocator?

**Comment by gilv** [comment]
@ImErick Hadoop eco-system never write single file..it always blocks / or parts, etc. Why you need single file?

**Comment by ImErick** [comment]
@gilv well, because I created a ETL pipeline, and one part of the requerimients it's in the L(oad) phase it's neccesary to have a one single CSV file in order to send to Cloud Object Storage and after that csv will be consume by DB2 table

**Comment by gilv** [comment]
@ImErick in this case there will be about 7 REST calls with non Stocator and about 2 REST calls with Stocator. You will not notice of course any difference for 1 object

**Comment by ImErick** [comment]
@gilv so, looks like I don't have any option, well thanks for your help :D
