### ISSUE TITLE
COSOutputStream: No space available in any of the local directories

### ISSUE THREAD

**Issue by student2028** [CODAIT/stocator#261]
I use spark 2.4 structured streaming and checkpoint to ibm cos, the spark job run two days ,report error 
COSOutputStream: No space available in any of the local directories
could you give me some advices? thanks

**Comment by student2028** [comment]
Now stocator is not support spark3.0 ?

**Comment by gilv** [comment]
@student2028 i don't understand the question...of course Stocator can work with Spark 3.X
"no space available" - the cluster where your Spark is running - may be some disks has no empty space?
