### ISSUE TITLE
Can I build the jar which includes a later version of the ibm-cos-sdk-java files?

### ISSUE THREAD

**Issue by stevehaertel** [CODAIT/stocator#270]
I noticed that when I followed the instructions to build the stocator jar file, I can see inside it that it took version 2.7.0 of the ibm-cos-sdk-java files. 

Is it possible to build the jar with a different (later) version of the ibm-cos-sdk-java?

**Comment by gilv** [comment]
@stevehaertel good point...will move it to 2.9.0

**Comment by stevehaertel** [comment]
Thank you @gilv

**Comment by flachasse** [comment]
The latest ibm-cos-sdk-java is now 2.9.1. Do I need to open anew issue so that it will be included in a future version of stocator-ibm-sdk?
