### ISSUE TITLE
Support for Spark 3.x?

### ISSUE THREAD

**Issue by raghukiran1224** [CODAIT/stocator#291]
Hi,

Does Stocator work with Spark 3.x? I see there are some dependency conflicts in the versions of Hadoop, etc for Spark 3.x and Stocator. When I create the `stocator` fat jar and use that with Spark 3.1, I run into Jackson consistency issues, whereas getting a thin jar and using that is missing a lot of dependencies.

Any guidance here will be helpful! Thanks!

**Comment by gilv** [comment]
@raghukiran1224 it suppose to work, may be indeed some minor version conflicts. We will check

**Comment by mrmadira** [comment]
Hi Raghu - For IBM-SDK branch, we moved internal dependency on jackson-databind from 2.10 to 2.12.0 recently to fix a twistlock scan issue. And this is working fine in our tests with Spark 3.1.2, 3.1.1 and Spark 3.0.2.  
For the master branch - the jackson-databind is still at 2.6.7.2.
Can you pls confirm where you are seeing the issues? And a little more detail on the error would help.

**Comment by raghukiran1224** [comment]
@mrmadira Thanks for the detailed explanation -- I will try the above and update the issue. @guykhazma had given me a similar feedback.

**Comment by mrmadira** [comment]
@raghukiran1224 - I hope things  are working fine now. Can you close this issue?

**Comment by raghukiran1224** [comment]
Yes, closing!
