### ISSUE TITLE
Upgrade version of jackson_databind and commons-codec as per twistlock scan

### ISSUE THREAD

**Issue by silpidhua** [CODAIT/stocator#304]
Upgrade version of jackson_databind to 2.13.1
and version of commons-codec to 1.13

**Comment by mrmadira** [comment]
https://github.com/CODAIT/stocator/pull/309 - Undo some of changes above for a simpler solution; IBM SDK branch merge
https://github.com/CODAIT/stocator/pull/310 - Corresponding master merge
