### ISSUE TITLE
Upgrade Amazon SDK

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/stocator#313]
Using Stocator with Amazon SDK 1.11, I noticed that when uploading large files, it makes 2 passes on an InputStream to calculate the MD5 checksum. This is fixed in Amazon SDK 1.12.283. Requesting Stocator upgrade to at least that version for the improvement.

**Comment by mrmadira** [comment]
Sure Bryan, we can take this up. cc @shivangi24

**Comment by shivangi24** [comment]
Updated aws sdk version to latest **1.12.338**
PR with master : https://github.com/CODAIT/stocator/pull/316
PR with 1.1.5-SNAPSHOT-ibm-sdk : https://github.com/CODAIT/stocator/pull/317

**Comment by BryanCutler** [comment]
Thanks @shivangi24 !

**Comment by mrmadira** [comment]
Bryan - can you check and close if it fixes your issue

**Comment by BryanCutler** [comment]
Yes, thank you
