### ISSUE TITLE
multiple partition object and create object with overwrite 

### ISSUE THREAD

**Issue by gilv** [CODAIT/stocator#99]
Assume object store contains:

container/d
container/d/part-001
container/d/part-002
container/_SUCCESS

We now call create method to create the same object in the overwrite mode. 
Assume that we now create object "d" that has smaller size, only 1 part.

Existing code will not delete previous object - but overwrite "d", "d/part-001". In this scenario old parts and even _SUCCESS method will exists from the previous run.

Create with overwrite mode should delete previous object, before creating another one. I assume calling delete method will be enough ( change should be in ObjectStoreFileSystem )

**Comment by gilv** [comment]
@djalova can you check it please?

**Comment by djalova** [comment]
@gilv Can you give me a sample application where this doesn't work?
In Spark, I can overwrite objects using the following:
`dataframe.write.mode(org.apache.spark.sql.SaveMode.Overwrite).format("csv").save("container/object")`
This deletes all the parts that exist in the path.

**Comment by gilv** [comment]
@djalova good point. In this flow Spark will automatically delete objects prior it creates them and there are no issues. But seems some flows allows overwrite mode and they don't perform delete. Perhaps it's a bug in Spark itself. Let's keep this issue as open and i will try to get more details on this. 
I agree, we need to reproduce it.
